[tools]
bat = "latest"
bun = "1.1.42"
"cargo:eza" = "latest"
chezmoi = "2.56.0"
fd = "latest"
fzf = "latest"
node = "20.12.2"
"npm:yarn" = "1.22.22"
ripgrep = "latest"
rust = "1.83.0"
yazi = "latest"
zoxide = "latest"
